import Head from 'next/head';
import MainTemplate from '@/components/layouts/MainTemplate';
import Navbar from '@/components/layouts/Navbar';
import BannerSection from '@/components/section/BannerSection';
import InformationSection from '@/components/section/InformationSection';
import AccordionsSection from '@/components/section/AccordionsSection';
import Footer from '@/components/layouts/Footer';
import Seperator from '@/components/global/Seperator';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Frontierx task</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Seperator />
      <MainTemplate>
        <BannerSection />
        <InformationSection />
        <AccordionsSection />
      </MainTemplate>
      <Footer />
    </div>
  );
}
